// -*- JavaScript -*-

var pjsip = require('./pjsip.node');

for (var i in pjsip) {
    exports[i] = pjsip[i];
}

// Define status codes

exports.SC_TRYING = 100;
exports.SC_RINGING = 180;
exports.SC_CALL_BEING_FORWARDED = 181;
exports.SC_QUEUED = 182;
exports.SC_PROGRESS = 183;

exports.SC_OK = 200;
exports.SC_ACCEPTED = 202;

exports.SC_MULTIPLE_CHOICES = 300;
exports.SC_MOVED_PERMANENTLY = 301;
exports.SC_MOVED_TEMPORARILY = 302;
exports.SC_USE_PROXY = 305;
exports.SC_ALTERNATIVE_SERVICE = 380;

exports.SC_BAD_REQUEST = 400;
exports.SC_UNAUTHORIZED = 401;
exports.SC_PAYMENT_REQUIRED = 402;
exports.SC_FORBIDDEN = 403;
exports.SC_NOT_FOUND = 404;
exports.SC_METHOD_NOT_ALLOWED = 405;
exports.SC_NOT_ACCEPTABLE = 406;
exports.SC_PROXY_AUTHENTICATION_REQUIRED = 407;
exports.SC_REQUEST_TIMEOUT = 408;
exports.SC_GONE = 410;
exports.SC_REQUEST_ENTITY_TOO_LARGE = 413;
exports.SC_REQUEST_URI_TOO_LONG = 414;
exports.SC_UNSUPPORTED_MEDIA_TYPE = 415;
exports.SC_UNSUPPORTED_URI_SCHEME = 416;
exports.SC_BAD_EXTENSION = 420;
exports.SC_EXTENSION_REQUIRED = 421;
exports.SC_SESSION_TIMER_TOO_SMALL = 422;
exports.SC_INTERVAL_TOO_BRIEF = 423;
exports.SC_TEMPORARILY_UNAVAILABLE = 480;
exports.SC_CALL_TSX_DOES_NOT_EXIST = 481;
exports.SC_LOOP_DETECTED = 482;
exports.SC_TOO_MANY_HOPS = 483;
exports.SC_ADDRESS_INCOMPLETE = 484;
exports.AC_AMBIGUOUS = 485;
exports.SC_BUSY_HERE = 486;
exports.SC_REQUEST_TERMINATED = 487;
exports.SC_NOT_ACCEPTABLE_HERE = 488;
exports.SC_BAD_EVENT = 489;
exports.SC_REQUEST_UPDATED = 490;
exports.SC_REQUEST_PENDING = 491;
exports.SC_UNDECIPHERABLE = 493;

exports.SC_INTERNAL_SERVER_ERROR = 500;
exports.SC_NOT_IMPLEMENTED = 501;
exports.SC_BAD_GATEWAY = 502;
exports.SC_SERVICE_UNAVAILABLE = 503;
exports.SC_SERVER_TIMEOUT = 504;
exports.SC_VERSION_NOT_SUPPORTED = 505;
exports.SC_MESSAGE_TOO_LARGE = 513;
exports.SC_PRECONDITION_FAILURE = 580;

exports.SC_BUSY_EVERYWHERE = 600;
exports.SC_DECLINE = 603;
exports.SC_DOES_NOT_EXIST_ANYWHERE = 604;
exports.SC_NOT_ACCEPTABLE_ANYWHERE = 606;

exports.SC_TSX_TIMEOUT = exports.SC_REQUEST_TIMEOUT;
exports.SC_TSX_TRANSPORT_ERROR = exports.SC_SERVICE_UNAVAILABLE;

exports.CALL_STATE = {
    NULL: 0,
    CALLING: 1,
    INCOMING: 2,
    EARLY: 3,
    CONNECTING: 4,
    CONFIRMED: 5,
    DISCONNCTD: 6,
    TERMINATED: 7
};

var nextCallInstanceId = 0x40000000;
exports.generateCallInstanceId = function () {
    return nextCallInstanceId++;
}